[patch]
title = "BN6Daniel"
authors = ["ssbmars <46971717+ssbmars@users.noreply.github.com>"]
license = "MIT"

[versions.'1.0.0']
netplay_compatibility = "danielbn6v1.0.0"
[versions.'1.1.0']
netplay_compatibility = "danielbn6v1.1.0"
[versions.'1.2.0']
netplay_compatibility = "danielbn6v1.2.0"
